### ISSUE TITLE
Add "kill-switch" to GUI version of Autotyper

### ISSUE THREAD

**Issue by DevNullInc** [Matt529/CCAutotyper#10]
As far as I've seen, there is no way to make the program stop while it is typing causing some issues when it goes off the rails (or a server lags too badly and causes the code to get jumbled) either a way to stop the typing entirely or pause it in the GUI would be very useful.

**Comment by glossawy** [comment]
The intention is for there to be no need to interact with the GUI during an autotyping task because the fact that you may be autotyping could cause a mess in the GUI. So instead the GUI is hidden and JNativeHooks allows the program to listen to key presses on the system level on a separate thread. Using this I assigned the key-bindings listed on the ComputerCraft Forum Topic and Github page.

The keybindings are:
'alt+P' to pause the typing (say for lag or to do some other task you need the keyboard for
'alt+S' to stop the typing and to terminate the current operation

If this isn't working and you are on a laggy server (which may see some input lag though I REALLY don't think this has an effect on system level input unless your instance of minecraft is eating lots of resources) you should try clicking out of the window or trying to give focus back to the desktop or some other process.

If this is not working for you, please go to the logs folder where CCAutotyper.exe is and put a link to a pastebin of the log file here. That will offer the best clue on how to resolve this. Also let me know which version you are using.

**Comment by glossawy** [comment]
Please note the log files are named in such a way that the first 3 numbers are the date (mm-dd-yy) and the last 3 is the time of creation (hh#mm#ss) as a 24-hour clock.

If keybinds do not work this is an issue with JNativeHooks for a specific system and will need a workaround.

**Comment by glossawy** [comment]
Closed because there has been no response.
